---
title: "simmer"
output: html_document
date: "2023-01-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("simmer")) install.packages("simmer")
library("simmer")
```

The single customer bank example:

```{r Single customer bank example with no server}
set.seed(10212)
customer <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  timeout(1) %>%
  log_("I must leave")

bank <-
  simmer("bank") %>%
  add_generator("Customer", customer, at(rexp(5, 1/5)))

bank %>% run(until = 1000)
# mon = monitored
bank %>% get_mon_arrivals()
```

```{r loop example} 
# Function to specify a series of waiting times in a loop
loop <- function(...) {
    time_diffs <- c(...)
    i <- 0
    function() {
      if (i < length(time_diffs)) {
        i <<- i+1
      } else {
        i <<- 1
      }
      return(time_diffs[i])
    }
  }

customer <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  timeout(loop(7, 10, 20)) %>%
  log_("I must leave")


bank <-
  simmer("bank") %>%
  add_generator("Customer", customer, at(2, 5, 12))

bank %>% run(until = 400)
#> 2: Customer0: Here I am
#> 5: Customer1: Here I am
#> 9: Customer0: I must leave
#> 12: Customer2: Here I am
#> 15: Customer1: I must leave
#> 32: Customer2: I must leave
#> simmer environment: bank | now: 32 | next: 
#> { Monitor: in memory }
#> { Source: Customer | monitored: 1 | n_generated: 3 }
bank %>% get_mon_arrivals()
#>        name start_time end_time activity_time finished replication
#> 1 Customer0          2        9             7     TRUE           1
#> 2 Customer1          5       15            10     TRUE           1
#> 3 Customer2         12       32            20     TRUE           1
```


```{r Different generators}
# Create a template trajectory
customer <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  timeout(1) %>% # The timeout of 1 is a placeholder to be overwritten later
  log_("I must leave")

# Create three copies of the template
Klaus <- customer
Tony <- customer
Evelyn <- customer

# Modify the timeout of each copy
Klaus[2] <- timeout(trajectory(), 10)
Tony[2] <- timeout(trajectory(), 7)
Evelyn[2] <- timeout(trajectory(), 20)

# Check that the modifications worked
Klaus
#> trajectory: Customer's path, 3 activities
#> { Activity: Log          | message: Here I am, level: 0 }
#> { Activity: Timeout      | delay: 10 }
#> { Activity: Log          | message: I must lea..., level: 0 }
Tony
#> trajectory: Customer's path, 3 activities
#> { Activity: Log          | message: Here I am, level: 0 }
#> { Activity: Timeout      | delay: 7 }
#> { Activity: Log          | message: I must lea..., level: 0 }
Evelyn
#> trajectory: Customer's path, 3 activities
#> { Activity: Log          | message: Here I am, level: 0 }
#> { Activity: Timeout      | delay: 20 }
#> { Activity: Log          | message: I must lea..., level: 0 }

bank <-
  simmer("bank") %>%
  add_generator("Klaus", Klaus, at(5)) %>%
  add_generator("Tony", Tony, at(2)) %>%
  add_generator("Evelyn", Evelyn, at(12))

bank %>% run(until = 400)
#> 2: Tony0: Here I am
#> 5: Klaus0: Here I am
#> 9: Tony0: I must leave
#> 12: Evelyn0: Here I am
#> 15: Klaus0: I must leave
#> 32: Evelyn0: I must leave
#> simmer environment: bank | now: 32 | next: 
#> { Monitor: in memory }
#> { Source: Klaus | monitored: 1 | n_generated: 1 }
#> { Source: Tony | monitored: 1 | n_generated: 1 }
#> { Source: Evelyn | monitored: 1 | n_generated: 1 }
bank %>% get_mon_arrivals()
#>      name start_time end_time activity_time finished replication
#> 1   Tony0          2        9             7     TRUE           1
#> 2  Klaus0          5       15            10     TRUE           1
#> 3 Evelyn0         12       32            20     TRUE           1
```
```{r Random customers}
library(simmer)

set.seed(1289)

customer <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  timeout(12) %>%
  log_("I must leave")

bank <-
  simmer("bank") %>%
  add_generator("Customer", customer, function() {c(0, rexp(4, 1/10), -1)})

bank %>% run(until = 400)
#> 0: Customer0: Here I am
#> 12: Customer0: I must leave
#> 14.3114: Customer1: Here I am
#> 26.3114: Customer1: I must leave
#> 26.5588: Customer2: Here I am
#> 35.8506: Customer3: Here I am
#> 38.2706: Customer4: Here I am
#> 38.5588: Customer2: I must leave
#> 47.8506: Customer3: I must leave
#> 50.2706: Customer4: I must leave
#> simmer environment: bank | now: 50.2705868901582 | next: 
#> { Monitor: in memory }
#> { Source: Customer | monitored: 1 | n_generated: 5 }
bank %>% get_mon_arrivals()
#>        name start_time end_time activity_time finished replication
#> 1 Customer0    0.00000 12.00000            12     TRUE           1
#> 2 Customer1   14.31136 26.31136            12     TRUE           1
#> 3 Customer2   26.55882 38.55882            12     TRUE           1
#> 4 Customer3   35.85064 47.85064            12     TRUE           1
#> 5 Customer4   38.27059 50.27059            12     TRUE           1
```

```{r now with a queue}
library(simmer)

#set.seed(2222)
res <- best.results[sample(1:nrow(best.results), 1),]
lambda <- res$lambda
mu <- res$mu
bank4 <- simmer()

customer4 <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  set_attribute("start_time", function() {now(bank4)}) %>%
  seize("counter3") %>%
  log_(function() {paste("Waited: ", now(bank4) - get_attribute(bank4, "start_time"))}) %>%
  timeout(function() rexp(1, mu)) %>%
  release("counter3") %>%
  log_(function() {paste("Finished: ", now(bank4))})

bank4 <-
  simmer("bank4") %>%
  add_resource("counter3", 2) %>%  # Que can define the number of resources here
  add_generator("customer4", customer4, function() {c(rexp(200, lambda), -1)})

bank4 %>% run(until = Inf)
dd4 <- bank4 %>%
  get_mon_arrivals() %>%
  transform(waiting_time = end_time - start_time - activity_time)

dd4
mean(dd4$waiting_time)
res
```

```{r The counter example}
library(simmer)

set.seed(1234)

bank <- simmer()

customer <-
  trajectory("Customer's path") %>%
  log_("Here I am") %>%
  #set_attribute("start_time", function() {now(bank)}) %>%
  seize("counter") %>%
  log_(function() {paste("Waited: ", now(bank) - get_attribute(bank, "start_time"))}) %>%
  timeout(function() rexp(1, lambda)) %>%
  release("counter") %>%
  log_(function() {paste("Finished: ", now(bank))})

bank <-
  simmer("bank") %>%
  add_resource("counter") %>%
  add_generator("Customer", customer, function() {c(0, rexp(200, mu), -1)})

bank %>% run()
#> 0: Customer0: Here I am
#> 0: Customer0: Waited:  0
#> 12: Customer0: Finished:  12
#> 25.0176: Customer1: Here I am
#> 25.0176: Customer1: Waited:  0
#> 27.4852: Customer2: Here I am
#> 27.551: Customer3: Here I am
#> 37.0176: Customer1: Finished:  37.0175860496223
#> 37.0176: Customer2: Waited:  9.53241116646677
#> 44.9785: Customer4: Here I am
#> 49.0176: Customer2: Finished:  49.0175860496223
#> 49.0176: Customer3: Waited:  21.466591599012
#> 61.0176: Customer3: Finished:  61.0175860496223
#> 61.0176: Customer4: Waited:  16.0391307005949
#> 73.0176: Customer4: Finished:  73.0175860496223
#> simmer environment: bank | now: 73.0175860496223 | next: 
#> { Monitor: in memory }
#> { Resource: counter | monitored: TRUE | server status: 0(1) | queue status: 0(Inf) }
#> { Source: Customer | monitored: 1 | n_generated: 5 }
bank %>%
  get_mon_arrivals() %>%
  transform(waiting_time = end_time - start_time - activity_time)
```

